const express = require('express')
const app = express()
const router = require('./routes/UserRoutes')
const employerRoutes = require('./routes/EmployeeRoutes')
const jobRoutes=require('./routes/JobRoutes')
const connectDB = require('./config/db')
app.use(express.json())
app.use('/api/users',router)
app.use('/indeed/employer',employerRoutes)
app.use('/indeed/employer',jobRoutes)
connectDB()
app.get('/',(req,res)=>{
    res.send("API Started..")
})
console.log("my first command")
app.listen(5000,console.log("API Started.."))
