export const ADMIN_TOP_MOST_REVIEWED_SUCCESS = 'ADMIN_TOP_MOST_REVIEWED_SUCCESS';
export const ADMIN_TOP_MOST_REVIEWED_FAIL = 'ADMIN_TOP_MOST_REVIEWED_FAIL';

export const ADMIN_TOP_MOST_RATING_SUCCESS = 'ADMIN_TOP_MOST_RATING_SUCCESS ';
export const ADMIN_TOP_MOST_RATING_FAIL = 'ADMIN_TOP_MOST_RATING_FAIL';

export const ADMIN_TOP_MOST_JOBSEEKER_SUCCESS = 'ADMIN_TOP_MOST_JOBSEEKER_SUCCESS';
export const ADMIN_TOP_MOST_JOBSEEKER_FAIL = 'ADMIN_TOP_MOST_JOBSEEKER_FAIL';

export const ADMIN_GET_ALL_REVIEWS_SUCCESS = 'ADMIN_GET_ALL_REVIEWS_SUCCESS';
export const ADMIN_GET_ALL_REVIEWS_FAIL= 'ADMIN_GET_ALL_REVIEWS_FAIL';