

export const GET_JOB_APPLICANTS_REQUEST = 'GET_JOB_APPLICANTS_REQUEST'
export const GET_JOB_APPLICANTS_SUCCESS = 'GET_JOB_APPLICANTS_SUCCESS'
export const GET_JOB_APPLICANTS_FAIL = 'GET_JOB_APPLICANTS_FAIL'
export const GET_JOB_APPLICANTS_RESET = 'GET_JOB_APPLICANTS_RESET'
