export const JOBSEEKER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';
export const JOBSEEKER_LOGIN = 'JOBSEEKER_LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_ALL_JOBS = 'FETCH_ALL_JOBS';
export const ERROR = 'ERROR';
export const EMPLOYER_DETAILS_ADD = "EMPLOYER_DETAILS_ADD";
