export const JOBSEEKER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';
export const JOBSEEKER_LOGIN = 'JOBSEEKER_LOGIN';
export const ERROR = 'ERROR';